# Generated by Django 5.2.4 on 2025-08-07 00:53

import common.custom_validation_form
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('organization_id', models.AutoField(db_column='ORGANIZATION_ID', primary_key=True, serialize=False, verbose_name='組織ID')),
                ('organization_name', models.CharField(db_column='ORGANIZATION_NAME', error_messages={'invalid': '有効な組織名を入力してください。', 'max_length': '組織名は64文字以内で入力してください。'}, max_length=64, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='組織名*')),
                ('organization_description', models.TextField(blank=True, db_column='ORGANIZATION_DESCRIPTION', default='', error_messages={'blank': '組織説明は必須項目です。', 'invalid': '有効な組織説明を入力してください。', 'max_length': '組織説明は256文字以内で入力してください。'}, max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='組織説明')),
                ('organization_email', models.EmailField(blank=True, db_column='ORGANIZATION_EMAIL', default='', error_messages={'invalid': '有効な組織EMAILを入力してください。', 'max_length': '組織EMAILは254文字以内で入力してください。', 'unique': 'この組織EMAILはすでに使用されています。'}, max_length=254, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='組織EMAIL')),
                ('is_paid', models.BooleanField(db_column='IS_PAID', default=False, verbose_name='支払い済みフラグ')),
                ('is_email_checked', models.BooleanField(db_column='IS_EMAIL_CHECKED', default=False, verbose_name='メールチェックフラグ')),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織一覧',
                'db_table': 'ORGANIZATION_MODEL',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('subscription_id', models.AutoField(db_column='SUBSCRIPTION_ID', primary_key=True, serialize=False, verbose_name='サブスクリプションID')),
                ('subscription_name', models.CharField(db_column='SUBSCRIPTION_NAME', max_length=64, unique=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='サブスクリプション名')),
                ('subscription_title', models.CharField(blank=True, db_column='SUBSCRIPTION_TITLE', default='', max_length=64, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='サブスクリプションタイトル')),
                ('subscription_description', models.TextField(blank=True, db_column='SUBSCRIPTION_DESCRIPTION', default='', max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='サブスクリプション説明')),
                ('subscription_price', models.IntegerField(db_column='SUBSCRIPTION_PRICE', verbose_name='サブスクリプション価格')),
                ('account_limit', models.IntegerField(db_column='ACCOUNT_LIMIT', default=10, verbose_name='アカウント作成可能数')),
                ('matching_group_limit', models.IntegerField(db_column='MATCHING_GROUP_LIMIT', default=2, verbose_name='マッチンググループ作成数')),
                ('is_ai_enabled', models.BooleanField(db_column='IS_AI_ENABLED', default=False, verbose_name='AI利用フラグ')),
            ],
            options={
                'verbose_name': 'サブスクリプション',
                'verbose_name_plural': 'サブスクリプション一覧',
                'db_table': 'SUBSCRIPTION_MODEL',
            },
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_column='ACCOUNT_ID', error_messages={'invalid': '有効なアカウントIDを入力してください。（半角英数字8文字以上128文字以内）', 'unique': 'このアカウントIDはすでに使用されています。'}, max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{8,128}$')], verbose_name='アカウントID*')),
                ('account_name', models.CharField(db_column='ACCOUNT_NAME', error_messages={'invalid': '利用できない文字が含まれています。', 'max_length': 'アカウント名前は64文字以内で入力してください。'}, max_length=64, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='アカウント名前*')),
                ('account_description', models.TextField(blank=True, db_column='ACCOUNT_DESCRIPTION', default='', error_messages={'blank': 'アカウント説明は必須項目です。', 'invalid': '利用できない文字が含まれています。', 'max_length': 'アカウント説明は256文字以内で入力してください。'}, max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='アカウント説明')),
                ('auth_code', models.CharField(choices=[('0', '管理アカウント'), ('10', 'メンバーアカウント')], db_column='AUTH_CODE', max_length=32, verbose_name='権限コード')),
                ('member_number', models.IntegerField(db_column='MEMBER_NUMBER', default=0, verbose_name='メンバー番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=128, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(db_column='UPDATED_BY', max_length=128, null=True, verbose_name='更新者')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_setup_completed', models.BooleanField(db_column='IS_SETUP_COMPLETED', default=False, verbose_name='セットアップ完了フラグ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(db_column='ORGANIZATION_ID', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_organization', to='app_account.organizationmodel', verbose_name='組織')),
            ],
            options={
                'verbose_name': 'アカウント',
                'verbose_name_plural': 'アカウント一覧',
                'db_table': 'ACCOUNT_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistoryModel',
            fields=[
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_column='ORGANIZATION_ID', max_length=255, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='組織ID')),
                ('organization_name', models.CharField(db_column='ORGANIZATION_NAME', error_messages={'invalid': '有効な組織名を入力してください。', 'max_length': '組織名は64文字以内で入力してください。'}, max_length=64, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='組織名')),
                ('organization_email', models.EmailField(blank=True, db_column='ORGANIZATION_EMAIL', default='', error_messages={'invalid': '有効な組織EMAILを入力してください。', 'max_length': '組織EMAILは254文字以内で入力してください。', 'unique': 'この組織EMAILはすでに使用されています。'}, max_length=254, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='組織EMAIL')),
                ('payment_name', models.CharField(db_column='PAYMENT_NAME', error_messages={'invalid': '有効な支払い名義を入力してください。', 'max_length': '支払い名義は64文字以内で入力してください。'}, max_length=256, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='支払い名義')),
                ('payment_amount', models.DecimalField(db_column='PAYMENT_AMOUNT', decimal_places=2, error_messages={'decimal_places': '支払い金額は小数点以下2桁まで入力してください。', 'invalid': '有効な支払い金額を入力してください。', 'max_digits': '支払い金額は10桁以内で入力してください。'}, max_digits=10, verbose_name='支払い金額')),
                ('transaction_id', models.CharField(blank=True, db_column='TRANSACTION_ID', default='', error_messages={'invalid': '有効な取引IDを入力してください。', 'max_length': '取引IDは128文字以内で入力してください。'}, max_length=128, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='取引ID')),
                ('payment_date', models.DateTimeField(db_column='PAYMENT_DATE', verbose_name='支払日時')),
                ('start_date', models.DateTimeField(db_column='START_DATE', verbose_name='開始日')),
                ('expiration_date', models.DateTimeField(db_column='EXPIRATION_DATE', verbose_name='有効期限')),
                ('payment_method', models.CharField(choices=[('credit_card', 'クレジットカード'), ('bank_transfer', '銀行振込'), ('other', 'その他')], db_column='PAYMENT_METHOD', default='credit_card', max_length=20, verbose_name='支払い方法')),
                ('payment_status', models.CharField(choices=[('paid', '支払い済み'), ('pending', '未処理'), ('failed', '失敗'), ('refunded', '返金済み')], db_column='PAYMENT_STATUS', default='pending', max_length=20, verbose_name='支払いステータス')),
                ('subscription', models.ForeignKey(db_column='SUBSCRIPTION', on_delete=django.db.models.deletion.PROTECT, related_name='payment_histories', to='app_account.subscriptionmodel', verbose_name='サブスクリプション')),
            ],
            options={
                'verbose_name': '支払い履歴',
                'verbose_name_plural': '支払い履歴',
                'db_table': 'PAYMENTHISTORY_MODEL',
            },
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='subscription',
            field=models.ForeignKey(blank=True, db_column='SUBSCRIPTION_ID', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_subscription', to='app_account.subscriptionmodel', verbose_name='サブスクリプション'),
        ),
    ]
