# Generated by Django 5.2.4 on 2025-08-07 00:53

import common.custom_validation_form
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('tag_name', models.CharField(db_column='TAG', max_length=64, unique=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'コミュニケーションタグ',
                'verbose_name_plural': 'コミュニケーションタグ一覧',
                'db_table': 'COMMUNICATION_TAG',
            },
        ),
        migrations.CreateModel(
            name='HobbyTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('tag_name', models.CharField(db_column='TAG', max_length=64, unique=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='タグ')),
            ],
            options={
                'verbose_name': '趣味タグ',
                'verbose_name_plural': '趣味タグ一覧',
                'db_table': 'HOBBY_TAG',
            },
        ),
        migrations.CreateModel(
            name='ValueTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('tag_name', models.CharField(db_column='TAG', max_length=64, unique=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='タグ')),
            ],
            options={
                'verbose_name': '価値観タグ',
                'verbose_name_plural': '価値観タグ一覧',
                'db_table': 'VALUE_TAG',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('age', models.IntegerField(blank=True, db_column='AGE', default=None, null=True, verbose_name='年齢')),
                ('position', models.CharField(blank=True, db_column='POSITION', default='', max_length=64, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='役職・所属')),
                ('profile_image', models.CharField(choices=[('img/profile/default1_m.jpeg', '男性１'), ('img/profile/default2_m.jpeg', '男性２'), ('img/profile/default3_m.jpeg', '男性３'), ('img/profile/default4_m.jpeg', '男性４'), ('img/profile/default1_w.jpeg', '女性１'), ('img/profile/default2_w.jpeg', '女性２'), ('img/profile/default3_w.jpeg', '女性３'), ('img/profile/default4_w.jpeg', '女性４')], db_column='PROFILE_IMAGE', default='img/profile/default1_m.jpeg', max_length=256, verbose_name='プロフィール画像')),
                ('self_introduction', models.TextField(blank=True, db_column='SELF_INTRODUCTION', default='', max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='自己紹介')),
                ('final_education', models.CharField(blank=True, db_column='FINAL_EDUCATION', default='', max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='最終学歴')),
                ('preferred_partner_description', models.TextField(blank=True, db_column='PREFERRED_PARTNER_DESCRIPTION', default='', max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='一緒に働きたい人物像')),
                ('special_skills', models.TextField(blank=True, db_column='SPECIAL_SKILLS', default='', max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='特技・スキル')),
                ('account', models.OneToOneField(db_column='ACCOUNT', on_delete=django.db.models.deletion.CASCADE, related_name='profile_account', to=settings.AUTH_USER_MODEL, verbose_name='アカウント')),
                ('organization', models.ForeignKey(db_column='ORGANIZATION', on_delete=django.db.models.deletion.CASCADE, related_name='profile_organization', to='app_account.organizationmodel', verbose_name='組織')),
            ],
            options={
                'verbose_name': 'プロフィール',
                'verbose_name_plural': 'プロフィール一覧',
                'db_table': 'PROFILE',
            },
        ),
        migrations.CreateModel(
            name='PersonalityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('big_five_extraversion', models.IntegerField(db_column='BIG_FIVE_Extraversion', verbose_name='ビッグファイブ・外向性')),
                ('big_five_neuroticism', models.IntegerField(db_column='BIG_FIVE_Neuroticism', verbose_name='ビッグファイブ・情緒安定性')),
                ('big_five_openness', models.IntegerField(db_column='BIG_FIVE_Openness', verbose_name='ビッグファイブ・開放性')),
                ('big_five_agreeableness', models.IntegerField(db_column='BIG_FIVE_Agreeableness', verbose_name='ビッグファイブ・協調性')),
                ('big_five_conscientiousness', models.IntegerField(db_column='BIG_FIVE_Conscientiousness', verbose_name='ビッグファイブ・誠実性')),
                ('account', models.OneToOneField(db_column='ACCOUNT', on_delete=django.db.models.deletion.CASCADE, related_name='personality_account', to=settings.AUTH_USER_MODEL, verbose_name='アカウント')),
                ('communication_tags', models.ManyToManyField(blank=True, db_column='COMMUNICATION_TAGS', related_name='personality_communication_tags', to='app_profile.communicationtagmodel', verbose_name='コミュニケーションタグ')),
                ('hobby_tags', models.ManyToManyField(blank=True, db_column='HOBBY_TAGS', related_name='personality_hobby_tags', to='app_profile.hobbytagmodel', verbose_name='趣味タグ')),
                ('organization', models.ForeignKey(db_column='ORGANIZATION', on_delete=django.db.models.deletion.CASCADE, related_name='personality_organization', to='app_account.organizationmodel', verbose_name='組織')),
                ('value_tags', models.ManyToManyField(blank=True, db_column='VALUE_TAGS', related_name='personality_value_tags', to='app_profile.valuetagmodel', verbose_name='価値観タグ')),
            ],
            options={
                'verbose_name': 'パーソナリティ',
                'verbose_name_plural': 'パーソナリティ一覧',
                'db_table': 'PERSONALITY',
            },
        ),
    ]
