# Generated by Django 5.2.4 on 2025-08-07 00:53

import common.custom_validation_form
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingGroupModel',
            fields=[
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('group_id', models.AutoField(db_column='GROUP_ID', primary_key=True, serialize=False, verbose_name='グループID')),
                ('group_name', models.CharField(db_column='GROUP_NAME', error_messages={'invalid': '有効なグループ名を入力してください。', 'max_length': 'グループ名は64文字以内で入力してください。'}, max_length=64, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='グループ名')),
                ('group_description', models.TextField(blank=True, db_column='GROUP_DESCRIPTION', default='', error_messages={'invalid': '有効なグループ説明を入力してください。', 'max_length': 'グループ説明は256文字以内で入力してください。'}, max_length=256, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='グループ説明')),
                ('matching_type', models.CharField(choices=[('supervisor_matching', '上司マッチング'), ('subordinate_matching', '部下マッチング'), ('peer_matching', 'ペアマッチング')], db_column='MATCHING_TYPE', default='supervisor_matching', error_messages={'invalid': '有効なマッチングタイプを選択してください。', 'max_length': 'マッチングタイプは32文字以内で入力してください。'}, max_length=32, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='マッチングタイプ')),
                ('is_matching_completed', models.BooleanField(db_column='IS_MATCHING_COMPLETED', default=False, verbose_name='マッチング完了フラグ')),
                ('matching_candidates', models.ManyToManyField(blank=True, db_column='MATCHING_CANDIDATES', related_name='matching_group_candidates', to=settings.AUTH_USER_MODEL, verbose_name='マッチング候補者')),
                ('organization', models.ForeignKey(db_column='ORGANIZATION', on_delete=django.db.models.deletion.CASCADE, related_name='matching_group_organization', to='app_account.organizationmodel', verbose_name='所属組織')),
                ('owner_account', models.ForeignKey(db_column='OWNER_ACCOUNT', on_delete=django.db.models.deletion.CASCADE, related_name='matching_group_owner', to=settings.AUTH_USER_MODEL, verbose_name='オーナーアカウント')),
                ('target_user', models.ForeignKey(db_column='TARGET_USER', on_delete=django.db.models.deletion.CASCADE, related_name='matching_group_target_user', to=settings.AUTH_USER_MODEL, verbose_name='対象者')),
            ],
            options={
                'verbose_name': 'マッチンググループ',
                'verbose_name_plural': 'マッチンググループ',
                'db_table': 'MATCHING_GROUP_MODEL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingResultModel',
            fields=[
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='作成時刻')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=256, null=True, verbose_name='作成者')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', null=True, verbose_name='更新時刻')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', default='', max_length=256, null=True, verbose_name='更新者')),
                ('result_id', models.AutoField(db_column='RESULT_ID', primary_key=True, serialize=False, verbose_name='結果ID')),
                ('match_score', models.FloatField(blank=True, db_column='MATCH_SCORE', default=None, null=True, verbose_name='マッチングスコア')),
                ('reason_summary', models.TextField(blank=True, db_column='REASON_SUMMARY', default='', max_length=512, null=True, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='サマリー')),
                ('matching_method', models.CharField(choices=[('hybrid', 'ハイブリッドマッチング'), ('auto', '自動マッチング'), ('manual', '手動マッチング')], db_column='MATCHING_METHOD', default='hybrid', error_messages={'invalid': '有効なマッチング方法を選択してください。', 'max_length': 'マッチング方法は64文字以内で入力してください。'}, max_length=64, validators=[common.custom_validation_form.validate_no_dangerous_input], verbose_name='マッチング方法')),
                ('chosen_person', models.ForeignKey(blank=True, db_column='CHOSEN_PERSON', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_result_chosen', to=settings.AUTH_USER_MODEL, verbose_name='選ばれた人')),
                ('matching_group', models.ForeignKey(db_column='MATCHING_GROUP', on_delete=django.db.models.deletion.CASCADE, related_name='matching_result_group', to='app_matching.matchinggroupmodel', verbose_name='マッチンググループ')),
                ('organization', models.ForeignKey(db_column='ORGANIZATION', on_delete=django.db.models.deletion.CASCADE, related_name='matching_result_organization', to='app_account.organizationmodel', verbose_name='所属組織')),
                ('voter', models.ForeignKey(blank=True, db_column='VOTER', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_result_voter', to=settings.AUTH_USER_MODEL, verbose_name='投票者')),
            ],
            options={
                'verbose_name': 'マッチング結果',
                'verbose_name_plural': 'マッチング結果',
                'db_table': 'MATCHING_RESULT',
            },
        ),
    ]
